export { LoginComponent }  from "./login/login.component";
export { InicioComponent }  from "./inicio/inicio.component";
export { PrincipalComponent }  from "./principal/principal.component";
export { FaqComponent }  from "./faq/faq.component";
export { AuditoriaComponent}  from "./administracion/auditoria/auditoria.component";
export { BitacoraComponent}  from "./administracion/bitacora/bitacora.component";
export { ProveedoresComponent}  from "./administracion/proveedores/proveedores.component";
export { UsuariosComponent }  from "./administracion/usuarios/usuarios.component";
export { ArchivosComponent as EstadisticosArchivosComponent }  from "./estadisticos/archivos/archivos.component";
export { TicketsComponent as EstadisticosTicketsComponent }  from "./estadisticos/tickets/tickets.component";
export { ArchivosComponent as MonitorArchivosComponent }  from "./monitor/archivos/archivos.component";
export { TicketsComponent as MonitorTicketsComponent }  from "./monitor/tickets/tickets.component";
